# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in Top100Scary.gemspec
gemspec

gem "rake", "~> 13.0"
gem "nokogiri"
gem "bundler"
gem "actionview"
gem "rspec"
